SELECT DISTINCT
  TABLES.TABLE_NAME,
  TABLES.DATA_LENGTH,
  COLUMNS.COLUMN_NAME
FROM information_schema.TABLES, information_schema.COLUMNS
WHERE TABLES.TABLE_SCHEMA = "auctionru_2013" 
  AND TABLES.TABLE_NAME = COLUMNS.TABLE_NAME
  AND TABLES.TABLE_NAME LIKE '%virtuemart%' 
  AND TABLES.DATA_LENGTH > 0 
  AND ( COLUMNS.COLUMN_NAME LIKE '%product_id%' 
        OR 
        COLUMNS.COLUMN_NAME LIKE '%products_id%'
      ) 
  ORDER BY TABLES.DATA_LENGTH DESC
