SELECT
  auc13_virtuemart_products_ru_ru.virtuemart_product_id,
  auc13_virtuemart_products_ru_ru.product_s_desc,
  auc13_virtuemart_products_ru_ru.product_desc,
  auc13_virtuemart_products_ru_ru.product_name,
  auc13_virtuemart_products_ru_ru.slug,
  auc13_virtuemart_product_prices.virtuemart_product_price_id,
  auc13_virtuemart_product_prices.virtuemart_product_id,
  auc13_virtuemart_product_prices.product_price,
  auc13_virtuemart_products.virtuemart_product_id
FROM auc13_virtuemart_products
  INNER JOIN auc13_virtuemart_products_ru_ru
    ON auc13_virtuemart_products.virtuemart_product_id = auc13_virtuemart_products_ru_ru.virtuemart_product_id
  INNER JOIN auc13_virtuemart_product_prices
    ON auc13_virtuemart_product_prices.virtuemart_product_id = auc13_virtuemart_products_ru_ru.virtuemart_product_id AND auc13_virtuemart_product_prices.virtuemart_product_id = auc13_virtuemart_products.virtuemart_product_id
WHERE auc13_virtuemart_products.virtuemart_product_id = 583