--
-- Описание для таблицы auc13_geodesic_users_backup
--
CREATE TABLE IF NOT EXISTS auc13_geodesic_users_backup (
  id int(11) NOT NULL DEFAULT 0,
  username varchar(25) NOT NULL,
  email varchar(255) NOT NULL,
  email2 tinytext NOT NULL,
  newsletter int(11) NOT NULL DEFAULT 0,
  level int(11) NOT NULL DEFAULT 0,
  company_name varchar(50) NOT NULL,
  business_type int(11) NOT NULL DEFAULT 0,
  firstname varchar(50) NOT NULL,
  lastname varchar(50) NOT NULL,
  address varchar(50) NOT NULL,
  address_2 varchar(50) DEFAULT NULL,
  zip varchar(12) NOT NULL,
  city varchar(50) NOT NULL,
  state varchar(50) NOT NULL,
  country varchar(50) NOT NULL,
  phone varchar(50) NOT NULL,
  phone2 varchar(50) NOT NULL,
  fax varchar(50) DEFAULT NULL,
  url tinytext DEFAULT NULL,
  date_joined int(14) NOT NULL DEFAULT 0,
  communication_type int(11) NOT NULL DEFAULT 3,
  feedback_score int(11) NOT NULL DEFAULT 0,
  feedback_count int(11) NOT NULL DEFAULT 0,
  feedback_positive_count int(11) NOT NULL DEFAULT 0,
  rate_sum int(11) NOT NULL DEFAULT 0,
  rate_num int(11) NOT NULL DEFAULT 0,
  optional_field_1 text NOT NULL,
  optional_field_2 text NOT NULL,
  optional_field_3 text NOT NULL,
  optional_field_4 text NOT NULL,
  optional_field_5 text NOT NULL,
  optional_field_6 text NOT NULL,
  optional_field_7 text NOT NULL,
  optional_field_8 text NOT NULL,
  optional_field_9 text NOT NULL,
  optional_field_10 text NOT NULL,
  affiliate_html mediumtext NOT NULL,
  filter_id int(11) NOT NULL DEFAULT 0,
  expose_email int(11) NOT NULL DEFAULT 0,
  expose_company_name int(11) NOT NULL DEFAULT 0,
  expose_firstname int(11) NOT NULL DEFAULT 0,
  expose_lastname int(11) NOT NULL DEFAULT 0,
  expose_address int(11) NOT NULL DEFAULT 0,
  expose_city int(11) NOT NULL DEFAULT 0,
  expose_state int(11) NOT NULL DEFAULT 0,
  expose_country int(11) NOT NULL DEFAULT 0,
  expose_zip int(11) NOT NULL DEFAULT 0,
  expose_phone int(11) NOT NULL DEFAULT 0,
  expose_phone2 int(11) NOT NULL DEFAULT 0,
  expose_fax int(11) NOT NULL DEFAULT 0,
  expose_url int(11) NOT NULL DEFAULT 0,
  expose_optional_1 int(11) NOT NULL DEFAULT 0,
  expose_optional_2 int(11) NOT NULL DEFAULT 0,
  expose_optional_3 int(11) NOT NULL DEFAULT 0,
  expose_optional_4 int(11) NOT NULL DEFAULT 0,
  expose_optional_5 int(11) NOT NULL DEFAULT 0,
  expose_optional_6 int(11) NOT NULL DEFAULT 0,
  expose_optional_7 int(11) NOT NULL DEFAULT 0,
  expose_optional_8 int(11) NOT NULL DEFAULT 0,
  expose_optional_9 int(11) NOT NULL DEFAULT 0,
  expose_optional_10 int(11) NOT NULL DEFAULT 0,
  account_balance decimal(14, 4) NOT NULL DEFAULT 0.0000,
  date_balance_negative int(14) NOT NULL,
  balance_freeze int(3) NOT NULL DEFAULT 0,
  feedback_icon varchar(255) NOT NULL,
  storefront_header text NOT NULL,
  storefront_template_id int(11) NOT NULL DEFAULT 0,
  storefront_welcome_message text NOT NULL,
  storefront_on_hold int(11) NOT NULL DEFAULT 1,
  storefront_home_link varchar(255) NOT NULL,
  storefront_traffic_processed_at int(11) NOT NULL,
  last_login_time datetime NOT NULL,
  last_login_ip varchar(15) DEFAULT NULL,
  storefront_trials_used text NOT NULL,
  seller_buyer_data text DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX email (email),
  UNIQUE INDEX username (username)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 223
character SET utf8
COLLATE utf8_general_ci;