DELETE FROM `#__csvi_template_tables` WHERE `component` = 'com_virtuemart';
INSERT IGNORE INTO `#__csvi_template_tables` (`template_type_name`, `template_table`, `component`) VALUES
('calcexport', 'calcexport', 'com_virtuemart'),
('calcexport', 'virtuemart_calcs', 'com_virtuemart'),
('calcimport', 'calcimport', 'com_virtuemart'),
('calcimport', 'virtuemart_calcs', 'com_virtuemart'),
('categoryexport', 'categoryexport', 'com_virtuemart'),
('categoryexport', 'virtuemart_categories', 'com_virtuemart'),
('categoryimport', 'categoryimport', 'com_virtuemart'),
('categoryimport', 'virtuemart_categories', 'com_virtuemart'),
('couponexport', 'couponexport', 'com_virtuemart'),
('couponexport', 'virtuemart_coupons', 'com_virtuemart'),
('couponimport', 'couponimport', 'com_virtuemart'),
('couponimport', 'virtuemart_coupons', 'com_virtuemart'),
('customfieldimport', 'customfieldimport', 'com_virtuemart'),
('customfieldimport', 'virtuemart_customs', 'com_virtuemart'),
('customfieldexport', 'customfieldexport', 'com_virtuemart'),
('customfieldexport', 'virtuemart_customs', 'com_virtuemart'),
('manufacturercategoryimport', 'manufacturercategoryimport', 'com_virtuemart'),
('manufacturercategoryimport', 'virtuemart_manufacturercategories', 'com_virtuemart'),
('manufacturerexport', 'manufacturerexport', 'com_virtuemart'),
('manufacturerexport', 'virtuemart_manufacturers', 'com_virtuemart'),
('manufacturerimport', 'manufacturerimport', 'com_virtuemart'),
('manufacturerimport', 'virtuemart_manufacturers', 'com_virtuemart'),
('mediaexport', 'mediaexport', 'com_virtuemart'),
('mediaexport', 'virtuemart_medias', 'com_virtuemart'),
('mediaimport', 'mediaimport', 'com_virtuemart'),
('mediaimport', 'virtuemart_medias', 'com_virtuemart'),
('orderexport', 'orderexport', 'com_virtuemart'),
('orderexport', 'virtuemart_orders', 'com_virtuemart'),
('orderexport', 'virtuemart_order_userinfos', 'com_virtuemart'),
('orderimport', 'orderimport', 'com_virtuemart'),
('orderimport', 'virtuemart_orders', 'com_virtuemart'),
('orderimport', 'virtuemart_order_userinfos', 'com_virtuemart'),
('orderitemexport', 'orderitemexport', 'com_virtuemart'),
('orderitemexport', 'virtuemart_order_items', 'com_virtuemart'),
('orderitemimport', 'orderitemimport', 'com_virtuemart'),
('orderitemimport', 'virtuemart_order_items', 'com_virtuemart'),
('productexport', 'productexport', 'com_virtuemart'),
('productexport', 'virtuemart_products', 'com_virtuemart'),
('productimport', 'productimport', 'com_virtuemart'),
('productimport', 'virtuemart_products', 'com_virtuemart'),
('ratingexport', 'ratingexport', 'com_virtuemart'),
('ratingexport', 'virtuemart_rating_reviews', 'com_virtuemart'),
('ratingimport', 'ratingimport', 'com_virtuemart'),
('ratingimport', 'virtuemart_rating_reviews', 'com_virtuemart'),
('shopperfieldexport', 'shopperfieldexport', 'com_virtuemart'),
('shopperfieldexport', 'virtuemart_userfields', 'com_virtuemart'),
('shopperfieldimport', 'shopperfieldimport', 'com_virtuemart'),
('shopperfieldimport', 'virtuemart_userfields', 'com_virtuemart'),
('userinfoexport', 'userinfoexport', 'com_virtuemart'),
('userinfoexport', 'users', 'com_virtuemart'),
('userinfoexport', 'virtuemart_userinfos', 'com_virtuemart'),
('userinfoexport', 'virtuemart_vmusers', 'com_virtuemart'),
('userinfoimport', 'userinfoimport', 'com_virtuemart'),
('userinfoimport', 'users', 'com_virtuemart'),
('userinfoimport', 'virtuemart_userinfos', 'com_virtuemart'),
('userinfoimport', 'virtuemart_vmusers', 'com_virtuemart'),
('waitinglistexport', 'virtuemart_waitingusers', 'com_virtuemart'),
('waitinglistexport', 'waitinglistexport', 'com_virtuemart'),
('waitinglistimport', 'virtuemart_waitingusers', 'com_virtuemart'),
('waitinglistimport', 'waitinglistimport', 'com_virtuemart');

DELETE FROM `#__csvi_template_types` WHERE `component` = 'com_virtuemart';
INSERT IGNORE INTO `#__csvi_template_types` (`template_type_name`, `template_type`, `component`, `url`, `options`) VALUES
('categoryexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=category', 'file,fields,category,layout,email,limit'),
('categoryimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=category', 'file,fields,category,category_image,category_path,limit'),
('couponexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=coupon', 'file,fields,layout,email,limit'),
('couponimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=coupon', 'file,fields,limit'),
('manufacturercategoryimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=manufacturercategories', 'file,fields,manufacturer_category'),
('manufacturerexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=manufacturer', 'file,fields,manufacturer,layout,email,limit'),
('manufacturerimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=manufacturer', 'file,fields,manufacturer'),
('orderexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=orders', 'file,fields,order,layout,email,limit'),
('orderimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=orders', 'file,fields,limit'),
('orderitemexport', 'export', 'com_virtuemart', NULL, 'file,fields,orderitem,layout,email,limit'),
('orderitemimport', 'import', 'com_virtuemart', NULL, 'file,fields,order_item'),
('productexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=product', 'file,fields,product,layout,email,shipping,limit'),
('mediaexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=media', 'file,fields,layout,email,limit'),
('mediaimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=media', 'file,fields,media,media_image,media_path'),
('productimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=product', 'file,fields,product,image,product_path,limit'),
('ratingexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=ratings', 'file,fields,layout,email,limit'),
('ratingimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=ratings', 'file,fields'),
('customfieldimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=custom', 'file,fields,limit'),
('customfieldexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=custom', 'file,fields,layout,email,limit'),
('shopperfieldexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=userfields', 'file,fields,layout,email,limit'),
('shopperfieldimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=userfields', 'file,fields'),
('waitinglistexport', 'export', 'com_virtuemart', NULL, 'file,fields,layout,email,limit'),
('waitinglistimport', 'import', 'com_virtuemart', NULL, 'file,fields,limit'),
('userinfoexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=user', 'file,fields,userinfo,layout,email,limit'),
('userinfoimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=user', 'file,fields'),
('calcimport', 'import', 'com_virtuemart', 'index.php?option=com_virtuemart&view=calc', 'file,fields,calc,limit'),
('calcexport', 'export', 'com_virtuemart', 'index.php?option=com_virtuemart&view=calc', 'file,fields,calc,limit');